require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PersonalitiesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Personality. As you add validations to Personality, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PersonalitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all personalities as @personalities" do
      personality = Personality.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:personalities)).to eq([personality])
    end
  end

  describe "GET #show" do
    it "assigns the requested personality as @personality" do
      personality = Personality.create! valid_attributes
      get :show, {:id => personality.to_param}, valid_session
      expect(assigns(:personality)).to eq(personality)
    end
  end

  describe "GET #new" do
    it "assigns a new personality as @personality" do
      get :new, {}, valid_session
      expect(assigns(:personality)).to be_a_new(Personality)
    end
  end

  describe "GET #edit" do
    it "assigns the requested personality as @personality" do
      personality = Personality.create! valid_attributes
      get :edit, {:id => personality.to_param}, valid_session
      expect(assigns(:personality)).to eq(personality)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Personality" do
        expect {
          post :create, {:personality => valid_attributes}, valid_session
        }.to change(Personality, :count).by(1)
      end

      it "assigns a newly created personality as @personality" do
        post :create, {:personality => valid_attributes}, valid_session
        expect(assigns(:personality)).to be_a(Personality)
        expect(assigns(:personality)).to be_persisted
      end

      it "redirects to the created personality" do
        post :create, {:personality => valid_attributes}, valid_session
        expect(response).to redirect_to(Personality.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved personality as @personality" do
        post :create, {:personality => invalid_attributes}, valid_session
        expect(assigns(:personality)).to be_a_new(Personality)
      end

      it "re-renders the 'new' template" do
        post :create, {:personality => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested personality" do
        personality = Personality.create! valid_attributes
        put :update, {:id => personality.to_param, :personality => new_attributes}, valid_session
        personality.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested personality as @personality" do
        personality = Personality.create! valid_attributes
        put :update, {:id => personality.to_param, :personality => valid_attributes}, valid_session
        expect(assigns(:personality)).to eq(personality)
      end

      it "redirects to the personality" do
        personality = Personality.create! valid_attributes
        put :update, {:id => personality.to_param, :personality => valid_attributes}, valid_session
        expect(response).to redirect_to(personality)
      end
    end

    context "with invalid params" do
      it "assigns the personality as @personality" do
        personality = Personality.create! valid_attributes
        put :update, {:id => personality.to_param, :personality => invalid_attributes}, valid_session
        expect(assigns(:personality)).to eq(personality)
      end

      it "re-renders the 'edit' template" do
        personality = Personality.create! valid_attributes
        put :update, {:id => personality.to_param, :personality => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested personality" do
      personality = Personality.create! valid_attributes
      expect {
        delete :destroy, {:id => personality.to_param}, valid_session
      }.to change(Personality, :count).by(-1)
    end

    it "redirects to the personalities list" do
      personality = Personality.create! valid_attributes
      delete :destroy, {:id => personality.to_param}, valid_session
      expect(response).to redirect_to(personalities_url)
    end
  end

end
